### ISSUE TITLE
Looking for data dictionary for Icon Names/styles

### ISSUE THREAD

**Issue by Tmodurr** [jseppi/Leaflet.MakiMarkers#10]
I must be looking in the wrong place but can someone pass along the centralized location where I can view the actual icon names? 

Just looking for the icon options which I can use. 
var officeIcon = L.MakiMarkers.icon({icon: "rocket", color: "#b0b", size: "m"});

**Comment by jseppi** [comment]
You can find an array of names in `L.MakiMarkers.icons`: https://github.com/jseppi/Leaflet.MakiMarkers/blob/master/Leaflet.MakiMarkers.js#L20

This can get out of date, however, so you can also check the official Maki repo: https://github.com/mapbox/maki/tree/master/icons If you notice any that I'm missing in this plugin, please submit a PR!
