### ISSUE TITLE
Mapbox API token

### ISSUE THREAD

**Issue by ebellempire** [jseppi/Leaflet.MakiMarkers#11]
Hi, I'm using an older version of this very excellent and useful plugin (thank you!) and I'm wondering if you expect it will stop working in the future without a Mapbox API token (which is required in the new version).

**Comment by jseppi** [comment]
Thanks for the kind words!

I don't know for certain if/when they will deactivate the v3 API, but I do have a feeling it will happen. They are generally responsive to questions if you want to email them.
