### ISSUE TITLE
Update icons array with new maki icons

### ISSUE THREAD

**Issue by jseppi** [jseppi/Leaflet.MakiMarkers#12]
Mapbox has added several new Maki icons. Update `L.MakiMarkers.icons` to include the new ones.

Ref https://github.com/mapbox/maki/blob/master/layouts/all.json

**Comment by jseppi** [comment]
Or better yet, remove that array and mention the linked file as a place to get a list of all valid icons :)

**Comment by CouchFrancois** [comment]
unfortunately the mapbox marker api doesn't handle the new maki icons (https://github.com/mapbox/maki/issues/370)

so https://api.mapbox.com/v4/marker/pin-m-doctor.png?access_token= doesn't work

**Comment by jseppi** [comment]
Oh dang, that stinks :(
